### ISSUE TITLE
new issues from other packages

### ISSUE THREAD

**Issue by js08** [lijunle/depcheck-es6#85] opened 2015-10-20 18:13 UTC
Hi,

Does both the below issues are satisfied in our package
https://github.com/dylang/npm-check/issues/50
https://github.com/dylang/npm-check/issues/44

**Comment by lijunle** [comment] 2015-10-20 18:27
No for https://github.com/dylang/npm-check/issues/50, I think [david](https://github.com/alanshaw/david) may handle that case.

No idea if it is caused by depcheck or npm-check. Could you please do some investigation?

**Comment by lijunle** [comment] 2015-10-22 03:38
Close this issue because no follow-up discussion.

**Closed as completed by lijunle** 2015-10-22 03:38 UTC
Labels: question
