### ISSUE TITLE
Parser for coffeescript

### ISSUE THREAD

**Issue by mathieudutour** [lijunle/depcheck-es6#80] opened 2015-10-15 16:46 UTC
Adding a parser for coffeescript files would be awesome.

I'm not familiar with the code, we just need to find a parser?

**Comment by lijunle** [comment] 2015-10-15 18:33
Sorry, I am finding the root cause of #79. I will look into this when have time.

**Comment by lijunle** [comment] 2015-10-16 02:24
@mathieudutour I proposed a RP #82 for this. 

For simplicity, I just compile the CoffeeScript to JavaScript then construct the JavaScript AST from the generated JavaScript. This may get a bad performance.

Do you have suggestions?

**Comment by mathieudutour** [comment] 2015-10-16 07:54
No, looks good :+1:

**Comment by js08** [comment] 2015-10-20 16:04
@lijunle can we close it now

**Comment by lijunle** [comment] 2015-10-20 16:17
Not yet. @mathieudutour proposed another solution to support CoffeeScript. See #84.

**Comment by js08** [comment] 2015-10-20 16:20
@lijunle he committed right, you can close it right

**Comment by lijunle** [comment] 2015-10-20 16:34
Merged!

**Closed as completed by lijunle** 2015-10-20 16:34 UTC
Labels: feature

**Comment by lijunle** [comment] 2015-10-20 17:18
Release 0.5.6 to include this feature.
